apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-w81m
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-w81m
    app.kubernetes.io/part-of: ci10t-776-0078-app
  name: devfile-sample-w81m
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-w81m
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-w81m
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-776-0078-tenant/ci10t-776-0078-app/devfile-sample-w81m@sha256:080c8ee256808a12939d73fe7fe0ed70e4947063e2d07e65cdd4a94f14087cf3
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
