apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-w81m
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-w81m
    app.kubernetes.io/part-of: ci10t-776-0078-app
  name: devfile-sample-w81m
spec:
  ports:
  - name: "3001"
    port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: devfile-sample-w81m
status:
  loadBalancer: {}
